mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from challenges import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="challenges/challenge_list.html"), name='home'),
    # path('', views.ChallengesListView.as_view(), name='home'),
    path('sync_db/', views.sync_db, name='sync_db'),
    # path('sync_challenge/', views.SyncChallengeView.as_view(), name='sync_challenge'),
    path('<int:pk>/', views.ChallengeDetailView.as_view(), name='challenge-detail'),
    path('ajax_datatable/challenges/', views.ChallengesAjaxDatatableView.as_view(), name="ajax_datatable_challenges"),
    # path('ajax_datatable/permissions/', views.PermissionAjaxDatatableView.as_view(), name="ajax_datatable_permissions"),
]

mysite/challenges/models.py
from django.db import models


class Solution(models.Model):
	challenge = models.ForeignKey('Challenge', on_delete=models.CASCADE)
	html = models.TextField(default='')
	text = models.TextField()

# Create your models here.
class Challenge(models.Model):
	LANG_CHOICES=(
		('python','Python'),
		('c#','C#'),
		('c++','C++'),
		('java','Java'),
		('javascript','Javascript'),
		('php','PHP'),
		('ruby','Ruby'),
		('swift','Swift'),
	)
	c_id = models.CharField(max_length=200, default='')
	lang = models.CharField(max_length=40, default='python', choices =LANG_CHOICES)
	title = models.CharField(max_length=200)
	# url = models.CharField(max_length=200)
	desc = models.TextField(blank=True)
	instructions = models.TextField(blank=True)
	tags = models.CharField(max_length=200)
	difficulty = models.CharField(max_length=200)
	

mysite/challenges/views.py
from bs4 import BeautifulSoup
import os
from django.shortcuts import render
from django.views import generic
from django.views import View
from django.conf import settings
from ajax_datatable.views import AjaxDatatableView

from .models import Challenge, Solution

class ChallengesListView(generic.list.ListView):
    model = Challenge


class ChallengeDetailView(generic.detail.DetailView):
    model = Challenge

def sync_db(request):
    syncer = SyncChallenge()
    syncer.sync()
    return render(request,'challenges/sync_status.html', 
        {'errors':syncer.filesnotfound,'success': syncer.filessynced}) #('<br>'.join(syncer.filesnotfound))


class SyncChallenge:
    def __init__(self):
        self.folder = os.path.join(settings.BASE_DIR, '..','htmlfiles')
        self.filesnotfound = []
        self.filessynced = []

    def sync(self):
        for lang in ['Cplusplus','C#','Java','JavaScript','PHP','Python','Ruby','Swift']:
            fn = f'languages/challenges_{lang.lower()}.html'
            if os.path.exists(f'{self.folder}/{fn}'):
                self.parse_challenge_list(fn)

        for challenge in Challenge.objects.all():
            self.parse_challenge(challenge)

    def parse_challenge_list(self, fn):
        soup = self.get_soup(fn)
        challenges_list=[]
        for challenge in soup('a'):
            challenge_url = challenge.get('href')
            if challenge_url and 'challenge' in challenge_url:
                challenge_data = {
                    'c_id':challenge_url.replace('/challenge/',''),
                    'lang': fn.split('_')[1].split('.')[0]
                } # c_id,lang,title,url,desc,tags,difficulty
                if Challenge.objects.filter(c_id=challenge_data['c_id']): continue

                items = challenge.find_all(['div','h3'])
                for i,txt in enumerate(items):
                    if i==0: challenge_data['title'] = txt.string
                    if i==1: challenge_data['desc'] = txt.string
                    if i==2: challenge_data['tags'] = ','.join([t.contents[1] for t in txt('div')])
                    if i==len(items)-1: challenge_data['difficulty'] = txt.string
                
                if 'title' in challenge_data:
                    challenges_list.append(Challenge(**challenge_data))
        print('going to create:', challenges_list)
        Challenge.objects.bulk_create(challenges_list)

    def get_soup(self,fn):
        fp = open(f'{self.folder}/{fn}')
        return BeautifulSoup(fp.read(), 'html.parser')
    
    def parse_challenge(self,challenge):
        if not os.path.exists(f'{self.folder}/challenges/{challenge.c_id}.html'):
            self.filesnotfound.append(challenge.c_id)
            return

        # Parse Instruction
        soup = self.get_soup(f'challenges/{challenge.c_id}.html')
        instructions=soup.find_all("div", {"class": "instructions"})
        if instructions:
            challenge.instructions= str(instructions[0])
            challenge.save()

        # Parse Solution
        soup = self.get_soup(f'challenges/{challenge.c_id}_solution.html')
        solutions = [
            Solution.objects.get_or_create(challenge=challenge, text=sol.text, defaults={'html':str(sol)}) 
            for sol in soup.find_all("div", {"class": "CodeMirror-code"})
        ]

        self.filessynced.append(challenge.c_id)


class ChallengesAjaxDatatableView(AjaxDatatableView):
    model = Challenge
    initial_order = [["title", "asc"], ]

    column_defs = [
        AjaxDatatableView.render_row_tools_column_def(),
        {'name': 'id', 'visible': False, },
        {'name': 'title', 'visible': True },
        {'name': 'c_id', 'visible': True, },
        {'name': 'difficulty', 'visible': True, },
        {'name': 'desc', 'visible': False},
        {'name': 'lang', 'visible': False, },
        {'name': 'tags', 'visible': False, },        
        # {'name': 'app_label', 'foreign_field': 'content_type__app_label', 'visible': True, },
    ]

mysite/challenges/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Edabit{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	{% block css %}
    {% endblock %}
</head>
<body>
	<div class="container my-4">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
        	<a class="btn btn-primary" href="{% url 'home' %}">Home</a> | <a class="btn btn-info" href="{% url 'sync_db' %}">Sync Challenges</a><hr>
        	{% block content %}
            {% endblock %}
        </div>
      </div>
    </div>
    <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

mysite/challenges/templates/challenges/challenge_detail.html
{% extends 'base.html' %}

{% block content %}
  <p>{{object.title}}  <span class="badge badge-success">{{object.difficulty}}</span></p>
  <p class="text-muted"><small>{{object.c_id}} {{object.tags}}</small></p>
  {{object.instructions |safe}}

  <h2>Solutions</h2>
  {% for solution in object.solution_set.all %}
  <div class="card m-2">
  	<div class="card-body">
        {{solution.html |safe}}
  	</div>
  </div>
  {% endfor %}
{% endblock %}

mysite/challenges/templates/challenges/challenge_list.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'ajax_datatable/css/style.css' %}" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="{% static 'datatables/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'datatables/responsive.bootstrap4.min.css' %}">

{% endblock %}

{% block content %}
  <!-- <table class="table table-sm table-bordered dt-responsive nowrap compact" style="width:100%" id="tb_challengelist">
    <thead>
     <tr><th>SL NO.</th> <th>Title</th> <th>Difficulty</th><th>Url</th>  <th>Tags</th> <th>Desc</th></tr>
    </thead>
    <tbody>
     {% for challenge in object_list %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td><a href="{% url 'challenge-detail' challenge.id %}">{{challenge.title}}</a></td>
        <td>{{challenge.difficulty}}</td>
        <td>{{challenge.c_id}}</td>        
        <td>{{challenge.tags}}</td>
        <td>{{challenge.desc}}</td>
      </tr>
     {% endfor %}
     </tbody>
  </table> -->

<div class="table-responsive">
    <table id="datatable_challenges" width="100%" class="table table-striped table-bordered dt-responsive compact">
    </table>
</div>

{% endblock %}


{% block js %}
<script type="text/javascript" src="{% static 'ajax_datatable/js/utils.js' %}"></script>
<script src="{% static 'datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'datatables/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'datatables/responsive.bootstrap4.min.js' %}"></script>

<script type="text/javascript">
$(document).ready(function() {
    // $('#tb_challengelist').DataTable({
    //   "pageLength": 10,
    //   columnDefs: [
    //     {
    //       render: function (data, type, full, meta) {
    //         return "<div style='white-space:normal; width:90%;'>" + data + "</div>";
    //       },
    //       targets: 5
    //     }
    //  ]
    // });

    AjaxDatatableViewUtils.initialize_table(
      $('#datatable_challenges'),
      "{% url 'ajax_datatable_challenges' %}",
      {
          // extra_options (example)
          processing: false,
          autoWidth: false,
          full_row_select: true,
          scrollX: false
      },
    );
});
</script>


{% endblock %}

mysite/challenges/templates/challenges/sync_status.html
{% extends 'base.html' %}

{% block content %}
  <div class="card success">
    <div class="card-header">Files Synced:</div>
    <div class="card-body"><ol>
      {% for item in success %}
        <li>{{item}}</li>
      {% endfor %}</ol>
    </div>
  </div>
  <hr>
  <div class="card">
  	<div class="card-header">Files Not found:</div>
  	<div class="card-body">
      <ol>
  		{% for item in errors %}
		  	<li>{{item}}</li>
		  {% endfor %}
      </ol>
  	</div>
  </div>
  
{% endblock %}